name:    wannaplay-mock
version: "0.0.0"

dependencies:
- base >=4.9.1.0 && <5
- yesod-core
- text >=0.11 && <2.0

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  wannaplay-mock:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wannaplay-mock
